### ISSUE TITLE
Updating the component to the current MPAndroidChart Version

### ISSUE THREAD

**Issue by Noires** [Flash3001/MPAndroidChart.Xamarin#1]
Hello,
it would be really great if you could update it again. I would do it myself, but iam kinda unsure about some of the bindings inside.

Greetings Noires

**Comment by Flash3001** [comment]
I'll do it Noires.

I just need to finish solving some problems that have emerged from the iOS version. 

Thank you for the feedback.

**Comment by Noires** [comment]
Thank you for that quick response and you actually dont need to hurry for me.
I got it working for me by removing LineBuffer, CircleBuffer and adding the newest .arr .
So less work than i actually thought ^^'

But would be nice to have it in nuget ofc :)

Edit: Btw great job with this!

**Comment by Noires** [comment]
Would be great if you could upgrade it to the new 3.0b Version, since iam struggling with some of the Additions which are needed for the mapping. If you got time for this =)

**Comment by Flash3001** [comment]
Noires, I've just updated it to 2.2.5. 

I'll start working on 3.0b now. =D

**Comment by Flash3001** [comment]
@Noires I've just updated it to 3.0b1. 

The Nuget package was sent as a pre-release. You can find it in here https://www.nuget.org/packages/MPAndroidChart/3.0.0-beta1

**Comment by Noires** [comment]
Thank you for your work! =)
