### ISSUE TITLE
Can any provide me small smaple for XAMARIN Andriod for LineChart

### ISSUE THREAD

**Issue by RAMESHKUMAR502** [Flash3001/MPAndroidChart.Xamarin#11]
List<Entry> entries = new List<Entry>();
            entries.Add(new Entry(4f, 0));
            entries.Add(new Entry(8f, 1));
            entries.Add(new Entry(6f, 2));
            entries.Add(new Entry(2f, 3));
            entries.Add(new Entry(18f, 4));
            entries.Add(new Entry(9f, 5));

            LineDataSet dataset = new LineDataSet(entries, "TEST");

            LineData lineData = new LineData(dataset);
            //dataset.SetColors(ColorTemplate.COLORFUL_COLORS); //
            // dataset.SetDrawCubic(true);
            dataset.SetDrawFilled(true);
           mChart.Data = lineData;
               
       the LineData is get method how to assign data to graph

**Comment by Flash3001** [comment]
@RAMESHKUMAR502 did you manage to get it working?
