### ISSUE TITLE
Fatal signal 6 (SIGABRT), code -6

### ISSUE THREAD

**Issue by mjanulaitis** [Flash3001/MPAndroidChart.Xamarin#13]
I've added the library, compiled the app verified the chart loads with no data.  Once I apply data as in the sample you've provided in the other issue response, the app crashes with this error.  There is no stack trace.

**Comment by Flash3001** [comment]
@mjanulaitis There was an update to the library after February, do you still see this issue?

**Comment by mjanulaitis** [comment]
I've moved on to another project.  It'll be about a year until I get back to this.  Thanks for the update!
