### ISSUE TITLE
is this still maintained?

### ISSUE THREAD

**Issue by nicolgit** [Flash3001/MPAndroidChart.Xamarin#14]
I see recent commits on MPAndroidChart and 2 years old commits here...

thank you!

**Comment by Flash3001** [comment]
Hey @nicolgit, yes it is. 

I follow the major releases in https://github.com/PhilJay/MPAndroidChart/releases

The last major release was in 2016. We are up to version 3.0.2, which is the last one that contains bugfixes and minor changes.

**Comment by nicolgit** [comment]
ok good to know: I have asked because we are currently using in our app [Caledos Runner], thank you!
