### ISSUE TITLE
SetDescription(string) method is missing

### ISSUE THREAD

**Issue by Technosdragon** [Flash3001/MPAndroidChart.Xamarin#15]
Hello,
I'm having some trouble with the "SetDescription(string)" method as I get the following exception: "System.MissingMethodException: void MikePhil.Charting.Charts.Chart.SetDescription(string)". Is there another way to set the description in the graph?

**Comment by Silic0nS0ldier** [comment]
Yep! Just use the `Description` property.
```csharp
chart.Description.Text = "description goes here";
```
