### ISSUE TITLE
Dynamic chart not working correctly

### ISSUE THREAD

**Issue by elpeppe** [Flash3001/MPAndroidChart.Xamarin#2]
Hi, I'm facing an issue in your library adapted for Xamarin. More precisely, I'm developing an app which uses dynamic graphs, but, strangely enough, sometimes the leftmost value disappears(meaning that its label and its circle are not shown). Also, every now and then the label gets shifted a little bit(4, 7, 11, 12 in this case). Would you happen to know how to solve these problems? Thanks in advance.
![graph issue](https://cloud.githubusercontent.com/assets/20165272/16377976/6616c7e2-3c69-11e6-8b2c-d04c86e0c15d.png)

**Comment by Flash3001** [comment]
@elpeppe I can't actually help you with that, as it is related to the library itself. 

You can either open an issue on [MPAndroidChart github](https://github.com/PhilJay/MPAndroidChart/issues) or post it on StackOverflow.

**Comment by elpeppe** [comment]
Actually, PhilJay redirected me here saying that he has nothing to do with Xamarin ports, and then closed the issue.

**Comment by Flash3001** [comment]
I see it. 

I used the word 'port' on this library description but it was incorrect, the correct is a 'binding'.

A Xamarin Binding is just a way to allow us to use native libraries, written in this case, in Java. 

All the library does is create a bunch of classes and interface definitions, equal to the original library, but what their code does, is to call the code running in Java. 

As you can see in [here](https://github.com/Flash3001/MPAndroidChart.Xamarin/tree/master/Jars), the library itself is included.

I'm sorry for not being able to provide you with an answer that solves your problem.

**Comment by elpeppe** [comment]
Ok, don't worry, i'll try to explain this to the creator, thanks.
