### ISSUE TITLE
License

### ISSUE THREAD

**Issue by hartra344** [Flash3001/MPAndroidChart.Xamarin#3]
Is it possible to add a license file on here and Nuget. I work at Microsoft and we'd love to use your bindings but legal isn't allowing it because of the lack of a license.

**Comment by Flash3001** [comment]
Done!

Used the same as the original library.

I've already sent it to Nuget, but only for the preview version. Which binds the new version 3.0. 

If you need it for 2.2.5 let me know.

**Comment by mattchenderson** [comment]
I work with @hartra344, and it looks like we're currently using the following of yours:
- MPAndroidChart 2.2.3.2 https://www.nuget.org/packages/MPAndroidChart/2.2.3.2
- SwiftSupport 2.2.0 https://www.nuget.org/packages/Xamarin.SwiftSupport/2.2.0
- iOSCharts 2.2.4.1 https://www.nuget.org/packages/iOSCharts/2.2.4.1

Could you confirm that the same license applies to those versions? Thank you!

**Comment by Flash3001** [comment]
Yes, they do.

I just couldn't add the license link for those older versions because Nuget doesn't allow me to update it without updating the package.

**Comment by hartra344** [comment]
Thank You!
