### ISSUE TITLE
Constructor missing labels parameter?

### ISSUE THREAD

**Issue by malachib** [Flash3001/MPAndroidChart.Xamarin#4]
I see for native implementations if one wants to customize the X-axis labels, you do:

```
LineData data = new LineData(labels, dataset);
chart.setData(data);
```

However no such construct seems to exist for the C# binding.  Please help!  

EDIT: This might be under the 3.0 breaking change category.  Looking into axis formatters now (https://github.com/PhilJay/MPAndroidChart/wiki/The-AxisValueFormatter-interface)

**Comment by malachib** [comment]
Indeed, it was solved by using the technique in the link.  Thanks for making this binding for us!

**Comment by gsaldana** [comment]
Hi @malachib, can you explain me how do you achieve this? I'm trying to implement something similar but I never get that the GetFormattedValue method be called. So the text shown in XAxis is always numerical.

var XAxis = chart.XAxis;
XAxis.ValueFormatter = new AxisValueFormatter(labels);

thanks in advance
