### ISSUE TITLE
Xamarin Forms

### ISSUE THREAD

**Issue by galadril** [Flash3001/MPAndroidChart.Xamarin#7]
Can this project also been ported to Xamarin Forms??

**Comment by Flash3001** [comment]
@galadril Yes, it can. It is on the list of to-dos, but not with a big priority for now. 

I believe creating the Views and ViewRenderes for each of the Charts wouldn't be the biggest issue. The API surface for DataSets, custom markers etc is big and they don't share the same classes in C# (one is a binding for Java and the other one for Swift), so we'd need to create a third API/set of classes to translate to each of the other two (the API itself is almost identical, just some naming changes and some small differences in the original library).

**Comment by galadril** [comment]
Thanks for the reply! Ill keep an eye on this.

**Comment by Flash3001** [comment]
@galadril I just learned about https://github.com/bulubuloa/Ultimate-Xamarin-Forms-KIT it uses MPAndroidChart and IOSCharts.
